language: python
sudo : false
dist: trusty
addons:
  apt:
    packages:
    - &mesa_apt [libgl1-mesa-dri]
    - &full_apt [libegl1-mesa, cmake, xorg-dev, libglu1-mesa-dev, mercurial, libdbus-1-dev, libgl1-mesa-dev, libglu1-mesa-dev, libpulse-dev, libx11-dev, libxcursor-dev, libxext-dev, libxi-dev, libxinerama-dev, libxrandr-dev, libxss-dev, libxt-dev, libxv-dev, libxxf86vm-dev, libasound2-dev, libts-dev, libudev-dev, libsdl2-2.0-0]
matrix:
  include:
    - env: PYTHON=3.6
      os: linux
    - env: PYTHON=3.6
      os: osx
      language: generic
python:
  - "3.6"
before_install:
  # Fix screen resolution to 1280x1024x16 :
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
install:
  - pushd $PWD
  # ------------------- PYTHON ENVIRONNEMENT -------------------
  # Deactivate travis environnement :
  - deactivate
  # Miniconda installation :
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

  # Install dependencies :
  - conda create -q -n testenv python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib pip
  - source activate testenv
  - pip install mne nibabel setuptools PyOpenGL PyOpenGL_accelerate pandas

  # Install testing librairies :
  - pip install codecov pytest pytest-cov pytest-html

  # ------------------- VISBRAIN -------------------
  - pip install -e .
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script: py.test --cov --verbose
cache:
  apt: true
notifications:
    email: false
    slack: visbrainteam:lHdzZcFmXQczGlxJEDtQYqv9
after_success:
  - codecov

# screenshot tests are really slow on travis... but installing image librairies
# does't fix it.
# before_install:
#   - sudo apt-get -qq install libfreetype6-dev libjpeg-turbo-progs
# sudo: required
# py.test --cov --verbose --cov-report=html --html=report.html