version: 2
jobs:
    build:
      branches:
        ignore:
          - gh-pages
        only:
          - master
          - develop
      docker:
        - image: circleci/python:3.6-jessie
      steps:
        - checkout
        - run:
            name: Spin up Xvfb
            command: |
              /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render -noreset;
              echo "export DISPLAY=:99" >> $BASH_ENV;
        - run:
            name: Install miniconda
            environment:
              MINICONDA: $HOME/miniconda
              PATH: $MINICONDA/bin:$PATH
            command: |
              cd /home/circleci
              hash -r
              wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
              bash miniconda.sh -b -f -p $MINICONDA
              conda config --set always_yes yes
              conda update conda
              conda info -a
              conda create -n testenv python=3.6.0 numpy scipy pip cython
              source activate testenv
        - run:
            name: Setup Python environment
            command: |
              pip install git+https://github.com/vispy/vispy.git;
              pip install pytest pytest-travis-fold pytest-sugar;
              pip install mne nibabel pandas openpyxl tensorpac xlrd scikit-image;
              pip install git+https://github.com/hbldh/lspopt.git#egg=lspopt;
              ls -al /home/ubuntu/miniconda3;
              ls -al /home/ubuntu/miniconda3/bin;
              echo $PATH;
              echo $CIRCLE_BRANCH
              which python;
              which pip;
        - save_cache:
            key: pip-cache
            paths:
              - ~/.cache/pip
        - run:
            name: Install visbrain
            command: |
              cd /home/ubuntu/visbrain && pip install -e .;
        - restore_cache:
            keys:
              - data-cache
              - pip-cache
        - run:
            name: Run visbrain's test
            command: |
              pytest
        - save_cache:
            key: data-cache
            paths:
              - ~/.visbrain_data
